version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: coordinator_db_dev
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  coordinator-service:
    container_name: coordinator_service
    image: coordinator:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    volumes:
      - /var/tmp/composeFiles:/var/tmp/composeFiles
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --postgres-host=postgres
      - --debug
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-i",
          "-X POST",
          "http://coordinator-service:8000/graphql",
          "-H 'Content-Type: application/json'",
          "-d '{ \"query\": \"query { accountMetadata { network } }\" }'"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  default:
    name: coordinator-service
