version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: coordinator_db_dev
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  coordinator-service:
    container_name: coordinator_service
    image: coordinator:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    volumes:
      - .projects:/usr/projects
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --postgres-host=postgres
      - --debug
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-i",
          "-X POST",
          "http://coordinator-service:8000/graphql",
          "-H 'Content-Type: application/json'",
          "-d '{ \"query\": \"query { accountMetadata { network } }\" }'"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  proxy-redis:
    image: redis:7-alpine
    container_name: coordinator_cache
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  
  proxy-server:
    image: onfinality/subql-indexer-proxy:v0.3.3-1
    container_name: coordinator_proxy
    ports:
      - 8001:8001
    depends_on:
      "coordinator-service":
        condition: service_healthy
    restart: always
    command:
      - --port=8001
      - --auth
      - --debug
      - --jwt-secret=vOVH6sdmpNWjRRIqCc7rdxs
      - --network=testnet
      - --network-endpoint=https://polygon-mumbai.infura.io/v3/4458cf4d1689497b9a38b1d6bbf05e78
      - --redis-endpoint=redis://coordinator_cache
      - --token-duration=8 # query auth token validity [hours]
      - --secret-key=vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3
      - --service-url=http://coordinator-service:8000
      - --bootstrap=210.55.152.69:7370
      # - --bootstrap=210.55.152.69:7370 # if more, just add new line
networks:
  default:
    name: coordinator-service
